const icons={box:'M21 8l-9 5-9-5m9 5v9M3 7l9-5 9 5v10l-9 5-9-5z',video:'M15 10l6-4v12l-6-4M3 5h12v14H3z',spark:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',edit:'M16 3l5 5-12 12H4v-5zM13 6l5 5',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',download:'M12 3v12m-5-5l5 5 5-5M4 16v5h16v-5',plus:'M12 5v14M5 12h14',search:'M21 21l-6-6M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',check:'M5 12l4 4L19 6',play:'M8 4l12 8-12 8z',upload:'M12 16V3m-5 5l5-5 5 5M4 15v6h16v-6',clock:'M12 8v4l3 3M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',file:'M14 2H4v20h16V8zM14 2v6h6M8 12h8M8 16h8'};
const icon=n=>`<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${icons[n]||icons.box}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=['选品','对标视频','AI拆解','脚本重构','分镜生成','成片 / 导出'];
const navNames=['选品工作台','对标素材库','AI拆解','脚本重构','分镜工作台','成片任务'];
const navIcons=['box','video','spark','edit','grid','download'];
const products=[{id:'cup',name:'轻量随行保温杯',short:'随行杯',category:'家居日用',price:59.9,commission:25,audience:'通勤人群 / 学生',points:'轻量便携、长效保温、密封防漏',color:'#edf3ff'},{id:'lamp',name:'无线充电阅读台灯',short:'阅读灯',category:'数码生活',price:129,commission:20,audience:'学生 / 居家办公',points:'柔和灯光、亮度可调、无线充电',color:'#edf7f7'},{id:'bag',name:'大容量通勤托特包',short:'通勤包',category:'服饰配件',price:89,commission:30,audience:'都市女性 / 通勤人群',points:'大容量收纳、轻便耐用、简约百搭',color:'#f3f0fa'}];
const fresh=()=>({step:0,product:null,reference:null,analysis:null,script:null,shots:null,tasks:[],settings:{platform:'抖音',tone:'朋友分享',duration:'30',audience:''},custom:[]});
let state=fresh();let filter='全部',query='',busy=false,videoFile=null,videoUrl=null,renderBlob=null,renderUrl=null;
try{const saved=JSON.parse(localStorage.getItem('zaopian-v1'));if(saved?.version===1&&saved.state)state={...fresh(),...saved.state};}catch{}
const allProducts=()=>[...products,...state.custom];
function save(){try{localStorage.setItem('zaopian-v1',JSON.stringify({version:1,state}));}catch{toast('浏览器存储不可用，请导出制作资料保存');}}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000);}
function done(i){return !![state.product,state.reference,state.analysis,state.script,state.shots,state.tasks.length][i];}
function render(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">${icon('play')}</span><div><b>造片</b><small>带货内容生产工作台</small></div></div><div class="nav-label">内容生产</div><nav aria-label="工作台导航">${navNames.map((n,i)=>`<button class="nav-item ${i===state.step?'active':''}" data-step="${i}" ${i===state.step?'aria-current="page"':''}>${icon(navIcons[i])}${n}<span class="nav-num">0${i+1}</span></button>`).join('')}</nav><div class="sidebar-bottom"><span class="pill">原型体验 · V0.1</span><p>把一个好产品，变成一条好内容。</p><div class="user"><span class="avatar">S</span><div>Simon 的工作空间<small>本机草稿</small></div></div></div></aside><div class="workspace"><header class="topbar"><div class="breadcrumb">生产工作台 <b>/ ${navNames[state.step]}</b></div><div class="top-actions"><span class="saved">草稿保存在此浏览器</span><span class="pill">演示模式</span></div></header><main class="main"><div class="title-row"><div><h1>${navNames[state.step]}</h1><p class="subtitle">${['先选一个值得讲的产品，开始你的下一条带货短视频。','收集爆款参考，找到值得复用的内容结构。','拆出内容节奏，让每一个转化点都清晰可见。','保留有效结构，把故事换成你的产品。','把脚本变成镜头，让制作有据可依。','整理制作资料，生成可下载的分镜预览片。'][state.step]}</p></div><button class="btn" data-action="new">${icon('plus')}新建项目</button></div><div class="steps" aria-label="生产流程">${steps.map((n,i)=>`<button class="step ${i===state.step?'active':''} ${done(i)?'done':''}" data-step="${i}"><span class="step-no">${done(i)&&state.step!==i?icon('check'):i+1}</span><span>${n}<small>${done(i)?'已准备':'待处理'}</small></span></button>`).join('')}</div><div id="content">${page()}</div><div class="footer-note"><span>原型体验：商品数据、AI拆解与脚本建议为演示内容；请按实际商品信息核对。</span><span>造片工作台 / 2026</span></div></main></div></div>`;}
function page(){if(state.step===0)return productPage();if(!state.product)return empty('先为项目选择一个商品','选定商品后，素材、脚本与分镜会关联到同一个项目。',0,'前往选品');return [productPage,referencePage,analysisPage,scriptPage,shotsPage,tasksPage][state.step]();}
function empty(title,description,step,label){return `<div class="panel empty">${icon('grid')}<h3>${title}</h3><p>${description}</p><button class="btn primary" data-step="${step}">${label}</button></div>`;}
function nextBar(title,description,step,label,enabled=true){return `<div class="selection-bar"><div><b>${esc(title)}</b><p>${esc(description)}</p></div><button class="btn primary" data-step="${step}" ${enabled?'':'disabled'}>${label}</button></div>`;}
function projectSummary(){return `<div class="panel"><div class="panel-title"><h2>当前项目</h2><span class="tag">本机草稿</span></div><div class="stat-row"><span>推广商品</span><b>${esc(state.product.name)}</b></div><div class="stat-row"><span>目标售价</span><b>¥${Number(state.product.price).toFixed(2)}</b></div><div class="stat-row"><span>目标人群</span><b>${esc(state.settings.audience||state.product.audience)}</b></div><p class="muted" style="margin-top:15px">商品卖点<br>${esc(state.product.points)}</p></div>`;}
function referencePage(){return `<div class="grid-two"><div><div class="panel"><div class="panel-title"><h2>导入对标视频</h2><span class="tag">素材准备</span></div><div class="notice">本地视频可预览与下载，文件留在你的设备上。平台分享链接在这一版仅作记录，暂未接入抓取与下载服务。</div><form id="url-form"><label class="field"><span>视频链接或平台分享文案</span><textarea name="url" placeholder="粘贴抖音、小红书等平台分享链接" style="min-height:80px"></textarea></label><div class="inline-actions"><button class="btn primary" type="submit">保存视频链接</button><button class="btn" type="button" data-action="demo-reference">使用示例结构</button></div><p class="error" id="url-error" role="alert"></p></form><div style="border-top:1px solid #edf0f6;margin:22px 0"></div><label class="upload">${icon('upload')}<strong>选择本地对标视频</strong><span class="muted">MP4、MOV、WebM · 最大 100 MB</span><input id="video-upload" type="file" accept="video/mp4,video/quicktime,video/webm" aria-label="上传本地对标视频"></label></div>${state.reference?`<div class="panel"><div class="panel-title"><h2>已选对标素材</h2><span class="tag">${state.reference.kind==='demo'?'结构示例':state.reference.kind==='local'?'本地素材':'链接记录'}</span></div>${videoUrl?`<video controls src="${esc(videoUrl)}" aria-label="对标视频预览"></video>`:''}<div class="reference"><div class="poster">${state.reference.kind==='demo'?'前 3 秒<br>痛点切入':'对标<br>素材'}</div><div><h3>${esc(state.reference.name)}</h3><p class="muted">${esc(state.reference.description)}</p>${state.reference.url?`<a class="btn text" href="${esc(state.reference.url)}" target="_blank" rel="noopener noreferrer">打开原视频页面</a>`:''}</div>${videoFile?'<button class="btn small" data-action="download-original">下载原视频</button>':''}</div>${state.reference.kind==='local'&&!videoFile?'<p class="notice" style="margin-top:15px">重新打开页面后，请重新选择本地文件以恢复预览。文件本身不会保存在浏览器草稿中。</p>':''}</div>`:''}</div><div>${projectSummary()}<div class="panel"><h3>对标时重点看什么</h3>${['开头：用户为什么愿意停下来？','中段：产品如何解决具体问题？','结尾：用户为什么愿意进一步了解？'].map(t=>`<div class="checkline">${icon('check')}<span>${t}</span></div>`).join('')}<p class="small-caption" style="margin-top:13px">只借鉴结构与表达思路，重构为自己的商品内容。</p></div></div></div>${nextBar(state.reference?'素材已准备，开始拆解':'先导入一条对标素材','先试用示例结构，也可以导入自己的视频。',2,'进入 AI 拆解',!!state.reference)}`;}
function analysisPage(){if(!state.reference)return empty('还没有对标素材','导入本地视频、记录分享链接，或使用示例结构。',1,'导入对标视频');const a=state.analysis;return `<div class="grid-two"><div class="panel"><div class="panel-title"><h2>内容结构拆解</h2><span class="tag">${a?'演示分析结果':'等待拆解'}</span></div><div class="notice">当前没有连接视频识别或大模型。这一版生成的是基于商品卖点与备注的结构建议，不代表对上传视频的真实识别。</div><label class="field"><span>对标观察备注（可选）</span><textarea id="observation" placeholder="例如：开头用通勤漏水场景吸引注意，中间给出密封测试。">${esc(state.observation||'')}</textarea></label><button class="btn primary" data-action="analyze" ${busy?'disabled':''}>${icon('spark')}${busy?'正在整理结构…':a?'重新生成演示拆解':'生成演示拆解'}</button>${a?`<div class="timeline"><span></span><span></span><span></span><span></span></div>${a.map((r,i)=>`<div class="analysis-row"><div class="time">${r.time}</div><div><h3>${esc(r.title)}</h3><p>${esc(r.content)}</p><span class="tag">${['留住注意力','建立认同','提供依据','引导行动'][i]}</span></div></div>`).join('')}`:''}</div><div>${projectSummary()}<div class="panel"><h3>可复用的转化结构</h3><div class="checkline">${icon('check')}<span>具体生活场景，比堆叠产品参数更容易理解。</span></div><div class="checkline">${icon('check')}<span>用实拍或可信资料支撑卖点，不编造测试结果。</span></div><div class="checkline">${icon('check')}<span>价格、功效、库存与促销信息需要逐项核对。</span></div></div></div></div>${nextBar(a?'结构已整理，开始重构脚本':'完成拆解后继续','脚本将沿用痛点、场景、卖点与行动引导的结构。',3,'重构脚本',!!a)}`;}
function scriptPage(){if(!state.analysis)return empty('先整理对标结构','完成演示拆解后，再围绕你的商品重构脚本。',2,'前往 AI 拆解');return `<div class="grid-two"><div class="panel"><div class="panel-title"><h2>脚本编辑器</h2><span class="tag">${state.script?'可编辑草稿':'等待重构'}</span></div><div class="form-row"><label class="field"><span>发布平台</span><select data-setting="platform">${options(['抖音','小红书','视频号'],state.settings.platform)}</select></label><label class="field"><span>表达风格</span><select data-setting="tone">${options(['朋友分享','场景测评','直接讲解'],state.settings.tone)}</select></label><label class="field"><span>目标时长</span><select data-setting="duration">${['15','30','60'].map(v=>`<option value="${v}" ${state.settings.duration===v?'selected':''}>${v} 秒</option>`).join('')}</select></label><label class="field"><span>目标人群</span><input data-setting="audience" maxlength="100" value="${esc(state.settings.audience||state.product.audience)}"></label></div><button class="btn primary" data-action="script" ${busy?'disabled':''}>${icon('spark')}${state.script?'重新生成演示脚本':'生成演示脚本'}</button>${state.script?state.script.map((r,i)=>`<div class="script-block"><header><b>${i+1}. ${esc(r.title)}</b><span>${esc(r.time)}</span></header><label><span class="small-caption">${esc(r.title)}口播</span><textarea data-script="${i}" aria-label="${esc(r.title)}口播" maxlength="1000">${esc(r.text)}</textarea></label></div>`).join(''):'<div class="empty"><p>选择平台、时长与风格，生成第一版脚本。</p></div>'}</div><div><div class="panel"><h3>竖屏内容预览</h3><div class="phone"><span class="eyebrow">${esc(state.settings.platform)} · ${state.settings.duration}S</span><h3>${esc(state.product.name)}</h3><div class="caption">${esc(state.script?.[0]?.text||'从一个真实场景，讲清楚一个产品。')}</div><span class="phone-bottom">文字版预览 · 不含商品画面</span></div><p class="muted">${esc(state.settings.tone)} / ${esc(state.settings.audience||state.product.audience)}</p></div><div class="panel"><h3>脚本核对</h3><p class="muted">AI建议为演示模板。请确认商品卖点、实际价格和表达准确。修改口播后，重新生成分镜即可同步更新。</p></div></div></div>${nextBar(state.script?'脚本已准备，生成分镜':'先生成第一版脚本','口播可以直接编辑，草稿会自动保存在此浏览器。',4,'进入分镜工作台',!!state.script)}`;}
function options(list,current){return list.map(v=>`<option ${v===current?'selected':''}>${v}</option>`).join('');}
function shotsPage(){if(!state.script)return empty('还没有可用脚本','先生成并确认脚本，再把每一段拆成可执行的镜头。',3,'前往脚本重构');return `<div class="panel"><div class="panel-title"><div><h2>分镜清单</h2><p class="muted" style="margin-top:7px">${esc(state.product.name)} · 9:16 竖屏 · ${state.settings.duration} 秒</p></div><button class="btn primary" data-action="shots">${icon('grid')}${state.shots?'重新生成分镜':'生成分镜清单'}</button></div>${state.shots?state.shots.map((s,i)=>`<article class="shot"><div class="shot-number">${String(i+1).padStart(2,'0')}</div><div><div class="shot-head"><h3>${esc(s.title)}</h3><span class="tag">${esc(s.time)} · ${esc(s.camera)}</span></div><div class="shot-fields"><label class="field"><span>画面描述</span><textarea data-shot="${i}" data-key="visual" aria-label="镜头${i+1}画面描述" maxlength="1000">${esc(s.visual)}</textarea></label><label class="field"><span>字幕 / 口播</span><textarea data-shot="${i}" data-key="text" aria-label="镜头${i+1}字幕" maxlength="1000">${esc(s.text)}</textarea></label></div></div></article>`).join(''):'<div class="empty"><h3>让每一段脚本都有一个镜头</h3><p>生成分镜后，可编辑画面描述和字幕内容。</p></div>'}</div>${nextBar(state.shots?`${state.shots.length} 个镜头已准备`:'先生成分镜清单','下一步可创建制作任务、导出资料和生成文字分镜预览片。',5,'创建成片任务',!!state.shots)}`;}
function tasksPage(){if(!state.shots)return empty('先准备分镜','生成分镜清单后，即可创建制作任务与导出。',4,'前往分镜工作台');const task=state.tasks[0];return `<div class="grid-two"><div><div class="panel"><div class="panel-title"><h2>制作任务</h2><span class="tag">${state.settings.platform}</span></div><div class="notice">这一版可生成真实 WebM 文字分镜预览片。它不包含实拍商品、配音或 AI生成画面；正式成片服务尚未接入。</div>${task?`<div class="task-card"><div class="panel-title"><h3>${esc(task.name)}</h3><span class="pill">${task.status==='rendering'?'生成预览片中':task.status==='failed'?'预览生成失败':renderBlob?'预览片已生成':'制作资料就绪'}</span></div><p class="muted">${esc(task.created)} · ${state.shots.length} 镜头 · 9:16 · ${state.settings.duration} 秒</p>${busy?`<div class="progress"><div style="width:${task.progress||0}%"></div></div><p class="small-caption">请保持页面打开，预览片在你的设备上生成。</p>`:''}${renderUrl?`<video controls src="${esc(renderUrl)}" aria-label="分镜预览成片"></video>`:''}${task.error?`<p class="error">${esc(task.error)}</p>`:''}<div class="inline-actions" style="margin-top:18px"><button class="btn primary" data-action="render-video" ${busy?'disabled':''}>${icon('play')}${renderBlob?'重新生成预览片':'生成文字分镜预览片'}</button>${renderBlob?'<button class="btn" data-action="download-video">'+icon('download')+'下载 WebM 预览片</button>':''}</div><p class="small-caption" style="margin-top:12px">预览片时长按分镜设置生成，不添加背景音乐或配音。刷新页面后需重新生成视频。</p></div>`:`<div class="empty"><h3>分镜已就位，开始制作</h3><p>创建任务后，可导出脚本和镜头资料。</p><button class="btn primary" data-action="create-task">${icon('plus')}创建制作任务</button></div>`}</div><div class="panel"><h3>制作规格</h3><div class="stat-row"><span>画幅</span><b>9:16 竖屏</b></div><div class="stat-row"><span>预览分辨率</span><b>720 × 1280</b></div><div class="stat-row"><span>预览格式</span><b>WebM · 无音轨</b></div><div class="stat-row"><span>目标时长</span><b>${state.settings.duration} 秒</b></div></div></div><div class="panel"><div class="panel-title"><h2>导出中心</h2><span class="tag">${task?'已就绪':'待创建任务'}</span></div><div class="export-list">${[['script','口播脚本','TXT · 分段口播与时间标记'],['shots','分镜清单','CSV · 镜头、画面、口播'],['project','项目制作资料','JSON · 商品、参考、拆解与分镜']].map(([key,title,desc])=>`<div class="export-item"><div><b>${icon('file')}${title}</b><small>${desc}</small></div><button class="btn small" data-export="${key}" ${task?'':'disabled'}>${icon('download')}导出</button></div>`).join('')}</div><p class="muted" style="margin-top:22px">制作资料可以交给拍摄与剪辑同事。全部导出保留你的修改，不依赖外部生成服务。</p><div class="notice" style="margin-top:20px">草稿仅存放在当前浏览器，换设备无法自动同步。建议导出项目资料保存。</div></div></div>`;}
function invalidate(from){if(from<=2)state.analysis=null;if(from<=3)state.script=null;if(from<=4)state.shots=null;state.tasks=[];clearRendered();}
function clearRendered(){if(renderUrl)URL.revokeObjectURL(renderUrl);renderUrl=null;renderBlob=null;}
function syncDraftUI(){document.querySelectorAll('.steps .step').forEach((el,i)=>{el.classList.toggle('done',done(i));const label=el.querySelector('small');if(label)label.textContent=done(i)?'已准备':'待处理';});const next=document.querySelector('.selection-bar button');if(next){const target=Number(next.dataset.step);next.disabled=!done(target-1);}const caption=document.querySelector('.phone .caption');if(caption)caption.textContent=state.script?.[0]?.text||'从一个真实场景，讲清楚一个产品。';}
function setProduct(id){const p=allProducts().find(p=>p.id===id);if(!p)throw Error('商品不存在');if(state.product?.id!==id){state.product={...p};invalidate(2);state.settings.audience=p.audience;}save();render();return {id:p.id,name:p.name};}
function setReference(ref){state.reference=ref;invalidate(2);save();render();toast('对标素材已准备');}
function analyze(){const title=['痛点切入','场景代入','卖点证明','行动引导'];const content=[state.observation||`从${state.product.audience}的日常困扰切入，提出具体问题。`,`将${state.product.name}放入真实使用场景，交代适用人群。`,`重点呈现${state.product.points}，用实拍支撑表达。`,'给出经过核对的价格和商品信息，引导用户查看详情。'];state.analysis=title.map((t,i)=>({title:t,time:timeRanges()[i],content:content[i]}));state.script=null;state.shots=null;state.tasks=[];clearRendered();save();render();toast('演示结构已生成');}
function timeRanges(){const d=Number(state.settings.duration);const p=[0,Math.round(d*.1),Math.round(d*.33),Math.round(d*.77),d];return p.slice(0,4).map((v,i)=>`${v}–${p[i+1]}s`);}
function makeScript(){const p=state.product;const points=p.points.split(/[、，,]/).filter(Boolean);const direct=state.settings.tone==='直接讲解';const measure=state.settings.tone==='场景测评';const hook=state.observation?`今天从这个场景聊起：${state.observation}`:direct?`给${state.settings.audience||p.audience}介绍一下${p.name}。`:measure?`${p.name}适不适合日常使用？今天从实际场景看一看。`:`如果你也在找适合日常使用的${p.short}，这款可以先了解一下。`;const text=[hook,`这款${p.name}面向${state.settings.audience||p.audience}。先看它在日常场景中的使用方式，再判断是否适合你。`,`${state.settings.tone==='朋友分享'?'我会重点关注':'主要关注'}${points.join('、')}。具体表现要以实拍和商品说明为准，选购前记得核对规格。`,`当前参考价是 ${Number(p.price).toFixed(2)} 元，实际价格以商品页面为准。感兴趣可以查看详情，再根据自己的需求决定。`];if(state.settings.duration==='15'){text[1]=`${p.name}，适合${state.settings.audience||p.audience}。`;text[2]=`重点关注${points.slice(0,2).join('、')}，以商品说明为准。`;text[3]=`参考价 ${Number(p.price).toFixed(2)} 元，查看详情了解。`;}if(state.settings.duration==='60')text[2]+='拍摄时建议给每个卖点留出独立镜头，展示使用方法、细节与局限，避免只给结论。';state.script=state.analysis.map((a,i)=>({title:a.title,time:timeRanges()[i],text:text[i]}));state.shots=null;state.tasks=[];clearRendered();save();render();toast('演示脚本已生成，可以直接修改');}
function makeShots(){const p=state.product;const visuals=[`用${p.audience}的日常场景开场。用实际拍摄交代问题，不添加虚构对比。`,`中景展示${p.name}的使用过程，画面突出使用方式与适用场景。`,`特写展示${p.points}。每个卖点需用真实素材或商品资料支撑。`,`商品正面展示，叠加经核对的名称与价格，留出商品信息位置。`];state.shots=state.script.map((s,i)=>({...s,visual:visuals[i],camera:['近景','中景','特写','定帧'][i]}));state.tasks=[];clearRendered();save();render();toast('分镜清单已生成');}
function createTask(){if(!state.shots)throw Error('请先生成分镜');state.tasks=[{id:'task-'+Date.now(),name:state.product.name+' · 带货短视频',status:'ready',created:new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}),progress:0}];clearRendered();save();render();toast('制作任务已创建');}
function showModal(html){const modal=document.querySelector('#modal');modal.innerHTML=html;modal.showModal();}
function newProject(){showModal(`<h2>开始一个新项目</h2><p class="muted">当前草稿将被替换。可以先导出资料保存，再开始新的选品。</p><div class="inline-actions"><button class="btn" data-action="close-modal">保留当前项目</button><button class="btn primary" data-action="confirm-new">开始新项目</button></div>`);}
function addProduct(){showModal(`<h2>添加你的商品</h2><form id="product-form"><label class="field"><span>商品名称</span><input name="name" required maxlength="40" placeholder="例如：轻量随行保温杯"></label><div class="form-row"><label class="field"><span>售价（元）</span><input name="price" type="number" required min="0.01" max="999999" step="0.01"></label><label class="field"><span>佣金率（%）</span><input name="commission" type="number" required min="0" max="100" step="0.1"></label></div><label class="field"><span>商品分类</span><select name="category">${options(['家居日用','数码生活','服饰配件'],'家居日用')}</select></label><label class="field"><span>核心卖点</span><input name="points" required maxlength="200" placeholder="用顿号分隔，例如：轻量便携、密封防漏"></label><label class="field"><span>目标人群</span><input name="audience" required maxlength="100" placeholder="例如：通勤人群 / 学生"></label><p class="error" id="product-error" role="alert"></p><div class="inline-actions"><button class="btn" type="button" data-action="close-modal">取消</button><button class="btn primary" type="submit">保存并选用</button></div></form>`);}
function download(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportFile(key){if(!state.tasks.length)return;const base=state.product.name.replace(/[\\/:*?"<>|]/g,'_');if(key==='project'){download(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),mode:'prototype',...state},null,2)],{type:'application/json'}),base+'-制作资料.json');}else if(key==='script'){download(new Blob(['\ufeff'+state.script.map(s=>`${s.time} ${s.title}\n${s.text}`).join('\n\n')],{type:'text/plain;charset=utf-8'}),base+'-口播脚本.txt');}else if(key==='shots'){const csvCell=v=>{let s=String(v);if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const rows=[['镜头','时间','内容段落','景别','画面描述','字幕口播'],...state.shots.map((s,i)=>[i+1,s.time,s.title,s.camera,s.visual,s.text])];download(new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),base+'-分镜清单.csv');}toast('已导出当前制作资料');}

// MediaRecorder's streaming WebM may omit Duration. Add it to Segment/Info,
// preserving the encoded frames so playback, seeking and re-import know the length.
async function withWebmDuration(blob,durationMs){
  if(!Number.isFinite(durationMs)||durationMs<=0)throw Error('无效的录制时长');
  const bytes=new Uint8Array(await blob.arrayBuffer());
  function elementAt(start){
    function vint(offset,id=false){
      const first=bytes[offset];let length=1,mask=128;
      while(length<=8&&!(first&mask)){length++;mask/=2;}
      if(!first||length>8||offset+length>bytes.length)throw Error('无效的 WebM 元素');
      let value=BigInt(id?first:first&(mask-1));
      for(let i=1;i<length;i++)value=value*256n+BigInt(bytes[offset+i]);
      return {length,value,unknown:!id&&value===(1n<<BigInt(length*7))-1n};
    }
    const id=vint(start,true),sizeStart=start+id.length,size=vint(sizeStart);
    const dataStart=sizeStart+size.length,end=size.unknown?bytes.length:dataStart+Number(size.value);
    if(!Number.isSafeInteger(end)||end>bytes.length)throw Error('不完整的 WebM');
    return {start,id:Number(id.value),sizeStart,dataStart,end,unknown:size.unknown};
  }
  function find(start,end,id){for(let p=start;p<end;){const e=elementAt(p);if(e.end>end)throw Error('无效的 WebM 结构');if(e.id===id)return e;p=e.end;}return null;}
  function sizeBytes(size){let length=1;while(size>=2**(length*7)-1)length++;const out=new Uint8Array(length);let value=BigInt(size)|(1n<<BigInt(length*7));for(let i=length-1;i>=0;i--){out[i]=Number(value&255n);value>>=8n;}return out;}
  const segment=find(0,bytes.length,0x18538067);
  const info=segment&&find(segment.dataStart,segment.end,0x1549a966);
  if(!info||info.unknown)throw Error('WebM 缺少录制信息');
  const scaleElement=find(info.dataStart,info.end,0x2ad7b1);
  let scale=1000000;
  if(scaleElement){scale=0;for(const b of bytes.subarray(scaleElement.dataStart,scaleElement.end))scale=scale*256+b;}
  if(!Number.isFinite(scale)||scale<=0)throw Error('无效的 WebM 时间单位');
  const duration=new Uint8Array(11);duration.set([0x44,0x89,0x88]);new DataView(duration.buffer).setFloat64(3,durationMs*1000000/scale);
  const fields=[];
  for(let p=info.dataStart;p<info.end;){const e=elementAt(p);if(e.end>info.end)throw Error('无效的 WebM 信息');if(e.id!==0x4489&&e.id!==0xbf)fields.push(bytes.subarray(e.start,e.end));p=e.end;}
  const payload=new Blob([...fields,duration]),newInfo=new Blob([bytes.subarray(info.start,info.sizeStart),sizeBytes(payload.size),payload]);
  const delta=newInfo.size-(info.end-info.start);
  const segmentSize=segment.unknown?bytes.subarray(segment.sizeStart,segment.dataStart):sizeBytes(segment.end-segment.dataStart+delta);
  return new Blob([bytes.subarray(0,segment.sizeStart),segmentSize,bytes.subarray(segment.dataStart,info.start),newInfo,bytes.subarray(info.end)],{type:blob.type});
}

function readVideoDuration(url){
  return new Promise(resolve=>{
    const video=document.createElement('video');let settled=false;
    const finish=duration=>{if(settled)return;settled=true;clearTimeout(timeout);video.onloadedmetadata=video.ondurationchange=video.onseeked=video.onerror=null;video.removeAttribute('src');video.load();resolve(duration);};
    const check=()=>{if(Number.isFinite(video.duration)&&video.duration>0)finish(video.duration);};
    const timeout=setTimeout(()=>finish(null),8000);
    video.preload='metadata';video.muted=true;
    video.onloadedmetadata=()=>{check();if(!settled&&video.duration===Infinity){try{video.currentTime=1e10;}catch{finish(null);}}};
    video.ondurationchange=video.onseeked=check;video.onerror=()=>finish(null);video.src=url;
  });
}
async function renderVideo(){if(busy||!state.tasks.length)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){toast('当前浏览器不支持视频录制，请先导出制作资料');return;}const types=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'];const mimeType=types.find(t=>MediaRecorder.isTypeSupported(t));if(!mimeType){toast('当前浏览器不支持 WebM，请先导出制作资料');return;}busy=true;clearRendered();const task=state.tasks[0];task.status='rendering';task.error='';task.progress=0;render();let stream,recorder,ticker;try{const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1280;const ctx=canvas.getContext('2d');const shots=structuredClone(state.shots);const total=Number(state.settings.duration)*1000;function wrap(text,y,size,maxLines){ctx.font=`500 ${size}px sans-serif`;let line='',lines=0;for(const char of text){if(ctx.measureText(line+char).width>580){ctx.fillText(line,70,y);y+=size*1.6;line=char;if(++lines>=maxLines)return;}else line+=char;}if(line)ctx.fillText(line,70,y);}
function draw(elapsed){const ratio=Math.min(elapsed/total,.999);const bounds=[.1,.33,.77,1];const i=bounds.findIndex(v=>ratio<v);const shot=shots[Math.max(i,0)];ctx.fillStyle='#101e38';ctx.fillRect(0,0,720,1280);ctx.fillStyle='#215cff';ctx.fillRect(0,0,720,12);ctx.fillStyle='#a6bfe9';ctx.font='24px sans-serif';ctx.fillText(`造片 / 分镜预览 / ${Math.max(i,0)+1} OF ${shots.length}`,70,100);ctx.fillStyle='white';wrap(state.product.name,205,44,3);ctx.fillStyle='#477df3';ctx.font='600 68px sans-serif';ctx.fillText(String(Math.max(i,0)+1).padStart(2,'0'),70,380);ctx.fillStyle='#dbe8ff';ctx.font='600 32px sans-serif';ctx.fillText(shot.title,70,445);ctx.fillStyle='#8ea9d3';wrap(shot.visual,525,26,6);ctx.fillStyle='#213756';ctx.fillRect(45,840,630,300);ctx.fillStyle='white';wrap(shot.text,895,30,4);ctx.fillStyle='#97afd3';ctx.font='22px sans-serif';ctx.fillText('文字分镜预览 · 无商品实拍 / 无配音',70,1200);ctx.fillStyle='#215cff';ctx.fillRect(0,1265,720*ratio,15);}
draw(0);stream=canvas.captureStream(15);recorder=new MediaRecorder(stream,{mimeType,videoBitsPerSecond:1500000});const chunks=[];const stopped=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||new Error('录制失败'));});recorder.start(300);const start=performance.now();ticker=setInterval(()=>{const elapsed=performance.now()-start;draw(elapsed);task.progress=Math.min(99,Math.round(elapsed/total*100));const bar=document.querySelector('.progress>div');if(bar)bar.style.width=task.progress+'%';if(elapsed>=total){clearInterval(ticker);recorder.stop();}},1000/15);await stopped;renderBlob=await withWebmDuration(new Blob(chunks,{type:mimeType}),total);if(!renderBlob.size)throw Error('未生成有效视频');renderUrl=URL.createObjectURL(renderBlob);task.status='ready';task.progress=100;toast('文字分镜预览片已生成');}catch(err){task.status='failed';task.error='视频生成未完成，请重试或导出制作资料。';}finally{clearInterval(ticker);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());busy=false;save();render();}}
function productPage(){const items=allProducts().filter(p=>(filter==='全部'||p.category===filter)&&p.name.includes(query));return `<div class="metrics"><div class="metric"><div><div class="metric-label">当前选品池</div><div class="metric-value">${allProducts().length}<small>个候选商品</small></div></div><span class="icon-tile">${icon('box')}</span></div><div class="metric"><div><div class="metric-label">已导入对标素材</div><div class="metric-value">${state.reference?1:0}<small>条参考视频</small></div></div><span class="icon-tile">${icon('video')}</span></div><div class="metric"><div><div class="metric-label">已创建成片任务</div><div class="metric-value">${state.tasks.length}<small>个制作任务</small></div></div><span class="icon-tile">${icon('grid')}</span></div></div><div class="section-head"><div class="inline-actions"><h2>候选商品</h2><span class="tag">示例选品池</span></div><button class="btn small" data-action="add-product">${icon('plus')}添加商品</button></div><div class="section-head"><div class="filters">${['全部','家居日用','数码生活','服饰配件'].map(c=>`<button class="filter ${c===filter?'active':''}" data-filter="${c}">${c}</button>`).join('')}</div><label class="search">${icon('search')}<input id="search" aria-label="搜索商品" placeholder="搜索商品名称" value="${esc(query)}"></label></div><div class="products">${items.map(p=>`<article class="product ${state.product?.id===p.id?'selected':''}"><div class="product-header"><div class="sku" style="background:${p.color}">${esc(p.short)}</div><div><h3>${esc(p.name)}</h3><span class="tag">${esc(p.category)}</span></div></div><div class="product-body"><div class="price"><small>¥</small>${Number(p.price).toFixed(2)}</div><div class="product-data"><div>预计佣金率<b>${p.commission}%</b></div><div>单笔预计佣金<b>¥${(p.price*p.commission/100).toFixed(2)}</b></div></div><p class="selling">${esc(p.points)}<br><span class="small-caption">适合：${esc(p.audience)}</span></p><button class="btn ${state.product?.id===p.id?'primary':''}" data-product="${p.id}">${state.product?.id===p.id?icon('check')+'已选为本项目商品':'选择此商品'}</button></div></article>`).join('')||'<div class="panel empty">没有匹配的商品，试试其他关键词。</div>'}</div><div class="selection-bar"><div><b>${state.product?'本项目商品：'+esc(state.product.name):'从选品开始你的生产流程'}</b><p>${state.product?'下一步：导入一条对标视频，提取内容结构。':'选择候选商品，或添加你正在经营的商品。'}</p></div><button class="btn primary" data-step="1" ${state.product?'':'disabled'}>导入对标视频</button></div>`;}
document.addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(busy){toast('请等待当前预览片完成');return;}if(target.dataset.step!==undefined){state.step=Number(target.dataset.step);save();render();}if(target.dataset.product){setProduct(target.dataset.product);toast('已选择 '+state.product.name);}if(target.dataset.filter){filter=target.dataset.filter;render();}if(target.dataset.export)exportFile(target.dataset.export);const action=target.dataset.action;if(action==='new')newProject();if(action==='add-product')addProduct();if(action==='close-modal')document.querySelector('#modal').close();if(action==='confirm-new'){const custom=state.custom;state=fresh();state.custom=custom;videoFile=null;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=null;clearRendered();save();render();document.querySelector('#modal').close();toast('新项目已创建');}if(action==='demo-reference'){if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=null;videoFile=null;setReference({kind:'demo',name:'通勤好物 · 痛点到转化结构',description:'30 秒结构示例 · 无真实视频文件'});}if(action==='analyze')analyze();if(action==='script')makeScript();if(action==='shots')makeShots();if(action==='create-task')createTask();if(action==='render-video')renderVideo();if(action==='download-original'&&videoFile)download(videoFile,videoFile.name);if(action==='download-video'&&renderBlob)download(renderBlob,state.product.name+'-分镜预览.webm');});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;const start=e.target.selectionStart;render();const el=document.querySelector('#search');el.focus();el.setSelectionRange(start,start);}if(e.target.id==='observation'){state.observation=e.target.value;invalidate(2);save();}if(e.target.dataset.script!==undefined){state.script[Number(e.target.dataset.script)].text=e.target.value;state.shots=null;state.tasks=[];clearRendered();save();}if(e.target.dataset.shot!==undefined){state.shots[Number(e.target.dataset.shot)][e.target.dataset.key]=e.target.value;state.tasks=[];clearRendered();save();}if(e.target.dataset.setting==='audience'){state.settings.audience=e.target.value;state.script=null;state.shots=null;state.tasks=[];clearRendered();save();}});
document.addEventListener('change',async e=>{if(e.target.dataset.script!==undefined||e.target.dataset.shot!==undefined||e.target.id==='observation')syncDraftUI();if(e.target.dataset.setting){state.settings[e.target.dataset.setting]=e.target.value;invalidate(3);save();render();}if(e.target.id==='video-upload'){const file=e.target.files[0];if(!file)return;if(!/\.(mp4|mov|webm)$/i.test(file.name)||file.size>100*1024*1024){toast('请选择 100 MB 以内的 MP4、MOV 或 WebM');return;}const url=URL.createObjectURL(file);e.target.value='';const duration=await readVideoDuration(url);if(!duration){URL.revokeObjectURL(url);toast('无法读取该视频，请换一个可播放的文件');return;}if(videoUrl)URL.revokeObjectURL(videoUrl);videoFile=file;videoUrl=url;setReference({kind:'local',name:file.name,description:`${Math.round(duration)} 秒 · ${(file.size/1024/1024).toFixed(1)} MB · 本地素材`,duration});}});
document.addEventListener('submit',e=>{if(e.target.id==='url-form'){e.preventDefault();const value=new FormData(e.target).get('url');const match=String(value).match(/https?:\/\/[^\s<>"'\u4e00-\u9fff]+/);try{if(!match)throw Error('请粘贴包含 http 或 https 链接的分享文案');const url=new URL(match[0]);if(!['http:','https:'].includes(url.protocol))throw Error('请输入有效的视频链接');if(videoUrl)URL.revokeObjectURL(videoUrl);videoFile=null;videoUrl=null;setReference({kind:'link',name:'对标视频 · '+url.hostname,url:url.href,description:'已记录原始链接 · 未下载 / 未识别视频'});}catch(err){document.querySelector('#url-error').textContent=err.message;}}if(e.target.id==='product-form'){e.preventDefault();const form=new FormData(e.target);const data=Object.fromEntries(form);if(!data.name.trim()||!data.points.trim()||!data.audience.trim()){document.querySelector('#product-error').textContent='请填写商品名称、卖点和目标人群。';return;}const p={id:'custom-'+Date.now(),name:data.name.trim(),short:data.name.trim().slice(0,3),price:Number(data.price),commission:Number(data.commission),category:data.category,points:data.points.trim(),audience:data.audience.trim(),color:'#edf3ff'};state.custom.push(p);filter='全部';query='';document.querySelector('#modal').close();setProduct(p.id);toast('商品已添加并选用');}});
for(const task of state.tasks){if(task.status==='rendering'){task.status='ready';task.progress=0;task.error='上次预览生成中断，可以重新生成。';}}
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_production_progress',description:'读取当前短视频项目完成步骤与商品，仅返回本机草稿摘要。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({product:state.product?.name||null,currentStep:steps[state.step],completed:steps.filter((_,i)=>done(i))})});document.modelContext.registerTool({name:'navigate_production_step',description:'切换工作台生产步骤，不生成内容或提交外部任务。',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:0,maximum:5}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(busy)throw Error('预览生成中，请稍后');if(!Number.isInteger(input.step)||input.step<0||input.step>5)throw Error('步骤必须为 0 到 5 的整数');state.step=input.step;save();render();return {step:steps[state.step]};}});}catch{}}
render();
